### PANDAS


¿Qué diferencia hay entre una Serie y un DataFrame?

1. La Serie 

        - Una Serie es el objeto fundamental unidimensional de Pandas.

        - Es esencialmente una columna de datos.
      
        - Contiene una matriz de datos (los valores) y un índice asociado, que son etiquetas que dan nombre a cada fila (por defecto, son números enteros desde 0).

        - Se asemeja a una lista de Python que ha sido mejorada con etiquetas de acceso rápido (el índice).

2. El DataFrame

        - El DataFrame es el objeto principal bidimensional de Pandas.

        - Es la estructura de datos más utilizada y representa una tabla con filas y columnas.

        - Puede verse como una colección de objetos Series que comparten el mismo índice de fila.

        - Es la forma en que Pandas representa la mayoría de los datos del mundo real, como hojas de cálculo o tablas de bases de datos.

- Tiene dos índices:

        - Índice de fila (eje 0): Las etiquetas de las filas.

        - Nombres de columna (eje 1): Las etiquetas de las columnas.

#### En resumen: el DataFrame es la tabla, y cada columna de esa tabla es una Serie.

#### Crea un array de dos dimensiones con 4 filas y 3 columnas.

Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

Descarga el archivo "medallas" y carga el DataFrame.

Usando el loc extrae todas las columnas de la fila de Tailandia.

Usando el loc extrae todas las columnas de China e Irán.

Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

Usando el iloc extrae la información de la India. Devolved todas las columnas.

Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

Contesta a las siguientes preguntas:

¿Qué país consiguió más de 200 medallas de oro?

¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

Momento de trabajar con Series. Contesta a las siguientes preguntas:



In [3]:
import pandas as pd
import numpy as np
import random

1. ARRAY

In [4]:
array = np.array([
    [10, 20, 30], 
    [15, 25, 35],  
    [12, 22, 32],
    [18, 28, 38]])

In [5]:
array

array([[10, 20, 30],
       [15, 25, 35],
       [12, 22, 32],
       [18, 28, 38]])

In [6]:
columnas = ["España", "Francia", "Italia"]

In [7]:
df = pd.DataFrame(array, columns=columnas )

In [8]:
df

,España,Francia,Italia
0,10,20,30
1,15,25,35
2,12,22,32
3,18,28,38


## Archivo Medallas

In [9]:
df = pd.read_csv("CSV/medallas.csv")

In [10]:
df

,Unnamed: 0,País,Oro,Plata,Bronce
0,1,China,1473,994,720
1,2,Japón,1032,1037,985
2,3,Corea del Sur,745,663,827
3,4,Irán,179,181,197
4,5,Kazajistán,155,158,224
5,6,India,154,202,315
6,7,Tailandia,132,175,278
7,8,Indonesia,112,131,240
8,9,China Taipéi,99,144,276
9,10,Corea del Norte,91,120,235


In [11]:
df.loc[7]

Unnamed: 0            8
País          Indonesia
Oro                 112
Plata               131
Bronce              240
Name: 7, dtype: object

In [12]:
df.loc[[1, 4]]

,Unnamed: 0,País,Oro,Plata,Bronce
1,2,Japón,1032,1037,985
4,5,Kazajistán,155,158,224


In [13]:
df.loc[[1, 4], ["Oro", "Plata", "Bronce"]]

,Oro,Plata,Bronce
1,1032,1037,985
4,155,158,224


In [14]:
df[df["País"] == "India"].index

Index([5], dtype='int64')

In [15]:
df.iloc[5]

Unnamed: 0        6
País          India
Oro             154
Plata           202
Bronce          315
Name: 5, dtype: object

In [16]:
df.iloc[1:10:2, [1]]

,País
1,Japón
3,Irán
5,India
7,Indonesia
9,Corea del Norte


In [17]:
df.iloc[1:10:2, [1, 2, 3,4]]

,País,Oro,Plata,Bronce
1,Japón,1032,1037,985
3,Irán,179,181,197
5,India,154,202,315
7,Indonesia,112,131,240
9,Corea del Norte,91,120,235


In [18]:
df["Oro"] > 200

0     True
1     True
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Oro, dtype: bool

In [19]:
df.loc[df["Oro"] > 200]

,Unnamed: 0,País,Oro,Plata,Bronce
0,1,China,1473,994,720
1,2,Japón,1032,1037,985
2,3,Corea del Sur,745,663,827


In [20]:
df.loc[(df["Oro"] > 200) & (df["Plata"] > 1000)]

,Unnamed: 0,País,Oro,Plata,Bronce
1,2,Japón,1032,1037,985


In [21]:
df.loc[(df["Oro"] > 200) | (df["Bronce"] > 700)]

,Unnamed: 0,País,Oro,Plata,Bronce
0,1,China,1473,994,720
1,2,Japón,1032,1037,985
2,3,Corea del Sur,745,663,827


In [22]:
df["Total"] = df["Oro"] + df["Plata"] + df["Bronce"]

df

,Unnamed: 0,País,Oro,Plata,Bronce,Total
0,1,China,1473,994,720,3187
1,2,Japón,1032,1037,985,3054
2,3,Corea del Sur,745,663,827,2235
3,4,Irán,179,181,197,557
4,5,Kazajistán,155,158,224,537
5,6,India,154,202,315,671
6,7,Tailandia,132,175,278,585
7,8,Indonesia,112,131,240,483
8,9,China Taipéi,99,144,276,519
9,10,Corea del Norte,91,120,235,446


#### Crea dos listas:

Una que se llame "valores" que tenga 7 números aleatorios.

Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más información sobre este método aquí.

Crea una Serie con el diccionario creado en el punto anterior.

¿Qué forma tiene esta última Serie?

¿Qué tipo de datos tiene?



In [23]:
valores = [random.randint(1, 50) for _ in range(7)]

In [24]:
valores 

[35, 4, 48, 47, 22, 17, 24]

In [25]:
indices = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]

In [28]:
s1 = pd.Series(valores, indices)

In [29]:
s1

lunes        35
martes        4
miercoles    48
jueves       47
viernes      22
sabado       17
domingo      24
dtype: int64

In [33]:
dicc = dict(zip(list(indices), list(valores)))

dicc

{'lunes': 35,
 'martes': 4,
 'miercoles': 48,
 'jueves': 47,
 'viernes': 22,
 'sabado': 17,
 'domingo': 24}

In [37]:
ind = list(indices)

In [36]:
val = list(valores)

In [44]:
dic = {} 

for v, i in zip(ind, val):
    dic[v] = i
    print(f"par agregado {i} y {v}")

par agregado 35 y lunes
par agregado 4 y martes
par agregado 48 y miercoles
par agregado 47 y jueves
par agregado 22 y viernes
par agregado 17 y sabado
par agregado 24 y domingo


In [45]:
dic

{'lunes': 35,
 'martes': 4,
 'miercoles': 48,
 'jueves': 47,
 'viernes': 22,
 'sabado': 17,
 'domingo': 24}

In [46]:
dic_serie = pd.Series(dic)
dic_serie

lunes        35
martes        4
miercoles    48
jueves       47
viernes      22
sabado       17
domingo      24
dtype: int64

In [47]:
dic_serie.shape

(7,)

In [48]:
dic_serie.dtype

dtype('int64')

¿Qué tamaño tiene?

¿Cuáles son los índices de la Serie?

¿Y los values?

Extrae el valor para el índice "lunes"

Extrae el valor para el índice "lunes", "martes" y "miércoles".

Extrae el valor para el índice "lunes" y "domingo".

In [49]:
dic_serie.size

7

In [50]:
dic_serie.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

In [51]:
dic_serie.values

array([35,  4, 48, 47, 22, 17, 24])

In [63]:
dic_serie.loc[['lunes', 'martes', 'miercoles']]

lunes        35
martes        4
miercoles    48
dtype: int64

In [65]:
dic_serie.loc[['lunes', 'domingo']].values

array([35, 24])